#!/usr/bin/env python3
"""
04_DIGIGARD_evaluate_catboost_classifier.py

DIGIGARD Stage 04: CatBoost-only post-training evaluation.

This stage runs AFTER:
    01_DIGIGARD_merge_and_clean_project_histories.py
    02_DIGIGARD_create_train_test_splits.py
    03_DIGIGARD_train_classifier.py

and evaluates ONE already-trained CatBoostClassifier run for ONE ground truth.

NO TRAINING OCCURS IN THIS SCRIPT.

The script loads:
    - the Stage-03 CatBoost model
    - the exact Stage-03 feature contract
    - the Stage-02 train.csv
    - the Stage-02 test.csv

It then evaluates the saved model on THREE datasets:

    1) FULL TARGET DATASET
       = Stage-02 train.csv + Stage-02 test.csv

    2) TRAINING DATASET
       = Stage-02 train.csv

    3) TESTING DATASET
       = Stage-02 test.csv

For EACH of those three datasets it performs:

A) FULL / NATURAL-DISTRIBUTION EVALUATION
    - full classification report
    - accuracy
    - balanced accuracy
    - precision
    - recall / sensitivity
    - specificity
    - F1
    - MCC
    - ROC AUC
    - average precision / PR AUC context
    - Brier score
    - log loss
    - confusion matrix
    - true-normalized confusion matrix
    - complete prediction/probability CSV
    - confusion-matrix plots
    - ROC curve
    - precision-recall curve

B) REPEATED BALANCED UNDERSAMPLED EVALUATION
    - repeated balanced 50/50 class subsets
    - configurable fraction of the minority class
    - same model probabilities reused; the model is NOT retrained
    - per-iteration metrics
    - per-iteration classification reports
    - mean/std metric summaries
    - mean/std classification-report summaries
    - mean confusion matrix
    - mean true-normalized confusion matrix
    - plots of the mean balanced confusion matrices

Default balancing follows the earlier DIGIGARD / OBJ evaluation philosophy:
    100 iterations
    90% of minority class retained per iteration
    same number sampled from majority class

Interpretation
--------------
TEST DATASET:
    This is the held-out Stage-02 test split and is the primary source for
    final generalization estimates.

TRAINING DATASET:
    These results are diagnostic/in-sample results because the saved model
    was trained using Stage-02 training data.

FULL TARGET DATASET:
    These results are descriptive because the dataset contains both training
    and test rows. They are NOT a replacement for the held-out test results.

Dependencies
------------
    pandas
    numpy
    scikit-learn
    matplotlib
    catboost
"""

from __future__ import annotations

import json
import math
import platform
import sys
import time
from importlib import metadata as importlib_metadata
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

from catboost import CatBoostClassifier

from sklearn.metrics import (
    accuracy_score,
    average_precision_score,
    balanced_accuracy_score,
    brier_score_loss,
    classification_report,
    confusion_matrix,
    f1_score,
    log_loss,
    matthews_corrcoef,
    precision_recall_curve,
    precision_score,
    recall_score,
    roc_auc_score,
    roc_curve,
)


# =============================================================================
# CONFIG: EDIT THESE FOR EACH EVALUATION RUN
# =============================================================================

# -------------------------------------------------------------------------
# ONE TARGET PER RUN.
# Must correspond to the target used in Stage 03.
# -------------------------------------------------------------------------
TARGET = "isBugPresent"

# Alternatives:
# TARGET = "isBugfix"
# TARGET = "isSZZBugIntroducer"


# -------------------------------------------------------------------------
# ONE CATBOOST STAGE-03 RUN PER EXECUTION.
#
# Use the exact run-folder name generated by Stage 03.
# -------------------------------------------------------------------------
MODEL_RUN = "catboost_default_rs42"

# Alternative if Stage 03 was run with Optuna:
# MODEL_RUN = "catboost_optuna_rs42"


# =============================================================================
# PIPELINE PATHS
# =============================================================================

RANDOM_STATE = 42

STAGE02_ROOT = Path("DIGIGARD_02_train_test_splits")
STAGE03_ROOT = Path("DIGIGARD_03_models")
STAGE04_ROOT = Path("DIGIGARD_04_catboost_evaluation")

STAGE02_TARGET_ROOT = STAGE02_ROOT / TARGET
SPLIT_DIR = STAGE02_TARGET_ROOT / f"splits_{RANDOM_STATE}"

TRAIN_CSV = SPLIT_DIR / "train.csv"
TEST_CSV = SPLIT_DIR / "test.csv"

MODEL_DIR = STAGE03_ROOT / TARGET / MODEL_RUN
MODEL_MANIFEST = MODEL_DIR / "model_manifest.json"
MODEL_FEATURES_JSON = MODEL_DIR / "features.json"
MODEL_PATH = MODEL_DIR / "best_model.cbm"

OUTPUT_DIR = STAGE04_ROOT / TARGET / MODEL_RUN


# =============================================================================
# THRESHOLD
# =============================================================================

# None:
#     use the default threshold stored by Stage 03 in model_manifest.json.
#
# Example:
#     THRESHOLD_OVERRIDE = 0.40
THRESHOLD_OVERRIDE: Optional[float] = None


# =============================================================================
# REPEATED BALANCED UNDERSAMPLING
# =============================================================================

N_BALANCED_ITERATIONS = 100
BALANCED_MINORITY_FRACTION = 0.90

# All three datasets use deterministic but separate seed ranges.
FULL_DATASET_BALANCE_SEED = RANDOM_STATE + 10_000
TRAIN_DATASET_BALANCE_SEED = RANDOM_STATE + 20_000
TEST_DATASET_BALANCE_SEED = RANDOM_STATE + 30_000


# =============================================================================
# OUTPUT SETTINGS
# =============================================================================

SAVE_PREDICTIONS = True
SAVE_PLOTS = True

# PNG is convenient for inspection; EPS is retained for paper workflows.
SAVE_PNG = True
SAVE_EPS = True

PLOT_DPI = 220

# If False, an existing Stage-04 evaluation directory causes the script to stop.
OVERWRITE_EXISTING_EVALUATION = True


# =============================================================================
# CONSTANTS
# =============================================================================

POSITIVE_CLASS = 1
NEGATIVE_CLASS = 0

DATASET_ORDER = [
    "full_dataset",
    "training_dataset",
    "testing_dataset",
]

DATASET_DISPLAY_NAMES = {
    "full_dataset": "Full target dataset (train + test)",
    "training_dataset": "Training dataset",
    "testing_dataset": "Testing dataset",
}

DATASET_INTERPRETATION = {
    "full_dataset": (
        "Descriptive evaluation on the union of Stage-02 train and test rows. "
        "Contains training observations and therefore is not an unbiased "
        "generalization estimate."
    ),
    "training_dataset": (
        "In-sample / diagnostic evaluation. The model was trained using "
        "Stage-02 training observations."
    ),
    "testing_dataset": (
        "Primary held-out generalization evaluation. Stage-02 test observations "
        "were not used for Stage-03 hyperparameter optimization, early stopping, "
        "or final training."
    ),
}


# =============================================================================
# CONFIG VALIDATION
# =============================================================================

if N_BALANCED_ITERATIONS <= 0:
    raise ValueError("N_BALANCED_ITERATIONS must be >= 1.")

if not 0.0 < BALANCED_MINORITY_FRACTION <= 1.0:
    raise ValueError(
        "BALANCED_MINORITY_FRACTION must be in (0, 1]."
    )

if THRESHOLD_OVERRIDE is not None:
    if not 0.0 < float(THRESHOLD_OVERRIDE) < 1.0:
        raise ValueError(
            "THRESHOLD_OVERRIDE must be strictly between 0 and 1."
        )


# =============================================================================
# GENERIC HELPERS
# =============================================================================

def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def write_json(
    path: Path,
    payload: Any,
) -> None:
    ensure_dir(path.parent)

    path.write_text(
        json.dumps(
            payload,
            indent=2,
            ensure_ascii=False,
            allow_nan=True,
        ),
        encoding="utf-8",
    )


def safe_package_version(
    package_name: str,
) -> Optional[str]:
    try:
        return importlib_metadata.version(
            package_name
        )
    except Exception:
        return None


def class_counts(
    y: pd.Series | np.ndarray,
) -> Dict[str, int]:
    counts = pd.Series(
        np.asarray(y, dtype=int)
    ).value_counts().sort_index()

    return {
        str(int(key)): int(value)
        for key, value in counts.items()
    }


def class_fractions(
    y: pd.Series | np.ndarray,
) -> Dict[str, float]:
    fractions = pd.Series(
        np.asarray(y, dtype=int)
    ).value_counts(
        normalize=True
    ).sort_index()

    return {
        str(int(key)): float(value)
        for key, value in fractions.items()
    }


def validate_binary_target(
    series: pd.Series,
    dataset_name: str,
) -> pd.Series:
    numeric = pd.to_numeric(
        series,
        errors="coerce",
    )

    if numeric.isna().any():
        raise ValueError(
            f"{dataset_name}: target '{TARGET}' contains "
            f"{int(numeric.isna().sum())} missing/non-numeric values."
        )

    observed = sorted(
        float(value)
        for value in pd.unique(numeric)
    )

    unexpected = [
        value
        for value in observed
        if value not in {0.0, 1.0}
    ]

    if unexpected:
        raise ValueError(
            f"{dataset_name}: target '{TARGET}' is not binary 0/1. "
            f"Unexpected values: {unexpected}"
        )

    y = numeric.astype(int)

    if y.nunique() != 2:
        raise ValueError(
            f"{dataset_name}: both classes are required. "
            f"Counts: {class_counts(y)}"
        )

    return y


def preprocess_numeric_features(
    df: pd.DataFrame,
    features: List[str],
    dataset_name: str,
) -> Tuple[pd.DataFrame, Dict[str, Any]]:
    """
    Apply the same deterministic numeric preparation used by Stage 03.

    No fitted transformation is performed.
    """
    missing_features = [
        feature
        for feature in features
        if feature not in df.columns
    ]

    if missing_features:
        raise ValueError(
            f"{dataset_name}: missing required model features:\n"
            + "\n".join(missing_features)
        )

    X = df[features].copy()

    coercion_losses: Dict[str, int] = {}

    for column in features:
        original = X[column]

        before_non_missing = int(
            original.notna().sum()
        )

        if pd.api.types.is_numeric_dtype(
            original
        ):
            converted = pd.to_numeric(
                original,
                errors="coerce",
            )
        else:
            text = (
                original
                .astype("string")
                .str.strip()
                .str.replace(
                    ",",
                    ".",
                    regex=False,
                )
            )

            converted = pd.to_numeric(
                text,
                errors="coerce",
            )

        after_non_missing = int(
            converted.notna().sum()
        )

        lost = max(
            0,
            before_non_missing
            - after_non_missing,
        )

        if lost > 0:
            coercion_losses[column] = lost

        X[column] = converted

    X = X.replace(
        [np.inf, -np.inf],
        np.nan,
    )

    preprocessing_report = {
        "dataset": dataset_name,
        "rows": int(len(X)),
        "feature_count": len(features),
        "numeric_coercions_to_nan":
            coercion_losses,
        "total_missing_cells":
            int(X.isna().sum().sum()),
        "rows_with_any_missing_feature":
            int(X.isna().any(axis=1).sum()),
        "rows_with_all_features_missing":
            int(X.isna().all(axis=1).sum()),
        "all_missing_features": [
            column
            for column in features
            if X[column].isna().all()
        ],
    }

    return X, preprocessing_report


# =============================================================================
# MODEL / CONTRACT LOADING
# =============================================================================

def load_model_manifest() -> Dict[str, Any]:
    if not MODEL_MANIFEST.exists():
        raise SystemExit(
            "Stage-03 model manifest not found:\n"
            f"  {MODEL_MANIFEST.resolve()}"
        )

    with MODEL_MANIFEST.open(
        "r",
        encoding="utf-8",
    ) as handle:
        manifest = json.load(handle)

    manifest_target = manifest.get(
        "target"
    )

    manifest_model_type = str(
        manifest.get(
            "model_type",
            "",
        )
    ).strip().upper()

    manifest_run_name = manifest.get(
        "run_name"
    )

    if manifest_target != TARGET:
        raise ValueError(
            "Target mismatch between Stage-04 config and "
            "Stage-03 model manifest:\n"
            f"  Stage 04 TARGET: {TARGET}\n"
            f"  Manifest target: {manifest_target}"
        )

    if manifest_model_type != "CATBOOST":
        raise ValueError(
            "Stage 04 is CatBoost-only.\n"
            f"Loaded Stage-03 model_type: "
            f"{manifest_model_type!r}"
        )

    if manifest_run_name != MODEL_RUN:
        raise ValueError(
            "MODEL_RUN mismatch:\n"
            f"  Stage 04 MODEL_RUN: {MODEL_RUN}\n"
            f"  Manifest run_name:  {manifest_run_name}"
        )

    return manifest


def load_feature_contract() -> List[str]:
    if not MODEL_FEATURES_JSON.exists():
        raise SystemExit(
            "Stage-03 features.json not found:\n"
            f"  {MODEL_FEATURES_JSON.resolve()}"
        )

    with MODEL_FEATURES_JSON.open(
        "r",
        encoding="utf-8",
    ) as handle:
        payload = json.load(handle)

    if isinstance(
        payload,
        list,
    ):
        features = list(payload)

    elif isinstance(
        payload,
        dict,
    ):
        features = list(
            payload.get(
                "features",
                [],
            )
        )

    else:
        raise ValueError(
            "Unsupported Stage-03 features.json format."
        )

    if not features:
        raise ValueError(
            "No features found in Stage-03 feature contract."
        )

    if len(features) != len(set(features)):
        raise ValueError(
            "Duplicate feature names found in Stage-03 feature contract."
        )

    return features


def resolve_threshold(
    manifest: Dict[str, Any],
) -> float:
    if THRESHOLD_OVERRIDE is not None:
        threshold = float(
            THRESHOLD_OVERRIDE
        )
        source = "THRESHOLD_OVERRIDE"

    else:
        threshold = float(
            manifest.get(
                "default_probability_threshold",
                0.50,
            )
        )
        source = (
            "Stage-03 model_manifest.json "
            "default_probability_threshold"
        )

    if not 0.0 < threshold < 1.0:
        raise ValueError(
            f"Resolved threshold must be in (0,1), got {threshold}."
        )

    print(
        f"[THRESHOLD] {threshold:.6g} "
        f"({source})"
    )

    return threshold


def load_catboost_model() -> CatBoostClassifier:
    if not MODEL_PATH.exists():
        raise SystemExit(
            "Stage-03 CatBoost model not found:\n"
            f"  {MODEL_PATH.resolve()}"
        )

    model = CatBoostClassifier()
    model.load_model(
        str(MODEL_PATH)
    )

    return model


# =============================================================================
# METRIC / REPORT HELPERS
# =============================================================================

def probability_to_class(
    probability_class1: np.ndarray,
    threshold: float,
) -> np.ndarray:
    p = np.asarray(
        probability_class1,
        dtype=float,
    )

    return (
        p >= threshold
    ).astype(int)


def classification_report_dict(
    y_true: np.ndarray,
    y_pred: np.ndarray,
) -> Dict[str, Any]:
    return classification_report(
        y_true,
        y_pred,
        labels=[0, 1],
        target_names=[
            "class_0",
            "class_1",
        ],
        output_dict=True,
        zero_division=0,
    )


def classification_report_text(
    y_true: np.ndarray,
    y_pred: np.ndarray,
) -> str:
    return classification_report(
        y_true,
        y_pred,
        labels=[0, 1],
        target_names=[
            "class_0",
            "class_1",
        ],
        output_dict=False,
        zero_division=0,
        digits=6,
    )


def classification_report_to_dataframe(
    report: Dict[str, Any],
) -> pd.DataFrame:
    rows: List[Dict[str, Any]] = []

    for label, values in report.items():
        if isinstance(
            values,
            dict,
        ):
            row = {
                "label": label,
                **values,
            }
        else:
            # sklearn returns plain accuracy as a scalar.
            row = {
                "label": label,
                "precision": np.nan,
                "recall": np.nan,
                "f1-score": float(values),
                "support": np.nan,
            }

        rows.append(row)

    return pd.DataFrame(rows)


def compute_metrics(
    y_true: np.ndarray,
    probability_class1: np.ndarray,
    threshold: float,
) -> Tuple[
    Dict[str, float],
    np.ndarray,
    np.ndarray,
    np.ndarray,
]:
    y = np.asarray(
        y_true,
        dtype=int,
    )

    p = np.asarray(
        probability_class1,
        dtype=float,
    )

    if len(y) != len(p):
        raise ValueError(
            "Target and probability lengths do not match."
        )

    pred = probability_to_class(
        p,
        threshold,
    )

    cm = confusion_matrix(
        y,
        pred,
        labels=[0, 1],
    )

    tn, fp, fn, tp = cm.ravel()

    specificity = (
        float(
            tn / (tn + fp)
        )
        if (tn + fp) > 0
        else float("nan")
    )

    negative_predictive_value = (
        float(
            tn / (tn + fn)
        )
        if (tn + fn) > 0
        else float("nan")
    )

    false_positive_rate = (
        float(
            fp / (fp + tn)
        )
        if (fp + tn) > 0
        else float("nan")
    )

    false_negative_rate = (
        float(
            fn / (fn + tp)
        )
        if (fn + tp) > 0
        else float("nan")
    )

    metrics: Dict[str, float] = {
        "accuracy":
            float(
                accuracy_score(
                    y,
                    pred,
                )
            ),
        "balanced_accuracy":
            float(
                balanced_accuracy_score(
                    y,
                    pred,
                )
            ),
        "precision":
            float(
                precision_score(
                    y,
                    pred,
                    zero_division=0,
                )
            ),
        "recall_sensitivity":
            float(
                recall_score(
                    y,
                    pred,
                    zero_division=0,
                )
            ),
        "specificity":
            specificity,
        "negative_predictive_value":
            negative_predictive_value,
        "false_positive_rate":
            false_positive_rate,
        "false_negative_rate":
            false_negative_rate,
        "f1":
            float(
                f1_score(
                    y,
                    pred,
                    zero_division=0,
                )
            ),
        "mcc":
            float(
                matthews_corrcoef(
                    y,
                    pred,
                )
            ),
        "true_positive_fraction":
            float(
                np.mean(y)
            ),
        "predicted_positive_fraction":
            float(
                np.mean(pred)
            ),
        "probability_mean":
            float(
                np.mean(p)
            ),
        "probability_std":
            float(
                np.std(p)
            ),
        "brier_score":
            float(
                brier_score_loss(
                    y,
                    p,
                )
            ),
        "tn":
            float(tn),
        "fp":
            float(fp),
        "fn":
            float(fn),
        "tp":
            float(tp),
    }

    try:
        metrics["roc_auc"] = float(
            roc_auc_score(
                y,
                p,
            )
        )
    except Exception:
        metrics["roc_auc"] = float(
            "nan"
        )

    try:
        metrics["average_precision"] = float(
            average_precision_score(
                y,
                p,
            )
        )
    except Exception:
        metrics["average_precision"] = float(
            "nan"
        )

    try:
        metrics["log_loss"] = float(
            log_loss(
                y,
                np.column_stack([
                    1.0 - p,
                    p,
                ]),
                labels=[0, 1],
            )
        )
    except Exception:
        metrics["log_loss"] = float(
            "nan"
        )

    normalized_cm = normalize_confusion_matrix_true(
        cm
    )

    return (
        metrics,
        cm,
        normalized_cm,
        pred,
    )


def normalize_confusion_matrix_true(
    cm: np.ndarray,
) -> np.ndarray:
    cm = np.asarray(
        cm,
        dtype=float,
    )

    row_sums = cm.sum(
        axis=1,
        keepdims=True,
    )

    with np.errstate(
        divide="ignore",
        invalid="ignore",
    ):
        normalized = np.divide(
            cm,
            row_sums,
            out=np.zeros_like(
                cm,
                dtype=float,
            ),
            where=row_sums != 0,
        )

    return normalized


def confusion_matrix_dataframe(
    cm: np.ndarray,
) -> pd.DataFrame:
    return pd.DataFrame(
        np.asarray(cm),
        index=[
            "true_0",
            "true_1",
        ],
        columns=[
            "pred_0",
            "pred_1",
        ],
    )


# =============================================================================
# PLOTTING
# =============================================================================

def save_figure(
    fig: plt.Figure,
    base_path: Path,
) -> None:
    ensure_dir(
        base_path.parent
    )

    if SAVE_PNG:
        fig.savefig(
            base_path.with_suffix(
                ".png"
            ),
            dpi=PLOT_DPI,
            bbox_inches="tight",
        )

    if SAVE_EPS:
        fig.savefig(
            base_path.with_suffix(
                ".eps"
            ),
            bbox_inches="tight",
        )

    plt.close(fig)


def plot_confusion_matrix(
    cm: np.ndarray,
    title: str,
    base_path: Path,
    value_format: str,
) -> None:
    if not SAVE_PLOTS:
        return

    matrix = np.asarray(
        cm,
        dtype=float,
    )

    fig, ax = plt.subplots(
        figsize=(6.5, 5.5)
    )

    image = ax.imshow(
        matrix,
        interpolation="nearest",
    )

    fig.colorbar(
        image,
        ax=ax,
        fraction=0.046,
        pad=0.04,
    )

    ax.set(
        xticks=[0, 1],
        yticks=[0, 1],
        xticklabels=[
            "Predicted 0",
            "Predicted 1",
        ],
        yticklabels=[
            "True 0",
            "True 1",
        ],
        ylabel="True class",
        xlabel="Predicted class",
        title=title,
    )

    threshold_for_text = (
        float(
            np.nanmax(matrix)
        ) / 2.0
        if matrix.size > 0
        else 0.0
    )

    for i in range(2):
        for j in range(2):
            value = matrix[i, j]

            if value_format == "integer":
                label = f"{value:.0f}"
            elif value_format == "float":
                label = f"{value:.3f}"
            else:
                label = str(value)

            # Black/white text depending on cell intensity.
            text_color = (
                "white"
                if value > threshold_for_text
                else "black"
            )

            ax.text(
                j,
                i,
                label,
                ha="center",
                va="center",
                color=text_color,
            )

    fig.tight_layout()

    save_figure(
        fig,
        base_path,
    )


def plot_roc_curve(
    y_true: np.ndarray,
    probability_class1: np.ndarray,
    title: str,
    base_path: Path,
) -> None:
    if not SAVE_PLOTS:
        return

    y = np.asarray(
        y_true,
        dtype=int,
    )

    p = np.asarray(
        probability_class1,
        dtype=float,
    )

    fpr, tpr, _ = roc_curve(
        y,
        p,
    )

    auc_value = roc_auc_score(
        y,
        p,
    )

    fig, ax = plt.subplots(
        figsize=(7.0, 6.0)
    )

    ax.plot(
        fpr,
        tpr,
        label=f"ROC AUC = {auc_value:.4f}",
    )

    ax.plot(
        [0, 1],
        [0, 1],
        linestyle="--",
        label="Random",
    )

    ax.set_xlabel(
        "False positive rate"
    )
    ax.set_ylabel(
        "True positive rate"
    )
    ax.set_title(
        title
    )
    ax.set_xlim(
        0,
        1,
    )
    ax.set_ylim(
        0,
        1.01,
    )
    ax.legend(
        loc="lower right"
    )
    ax.grid(
        alpha=0.25
    )

    fig.tight_layout()

    save_figure(
        fig,
        base_path,
    )


def plot_precision_recall_curve(
    y_true: np.ndarray,
    probability_class1: np.ndarray,
    title: str,
    base_path: Path,
) -> None:
    if not SAVE_PLOTS:
        return

    y = np.asarray(
        y_true,
        dtype=int,
    )

    p = np.asarray(
        probability_class1,
        dtype=float,
    )

    precision, recall, _ = (
        precision_recall_curve(
            y,
            p,
        )
    )

    ap_value = (
        average_precision_score(
            y,
            p,
        )
    )

    baseline = float(
        np.mean(y)
    )

    fig, ax = plt.subplots(
        figsize=(7.0, 6.0)
    )

    ax.plot(
        recall,
        precision,
        label=f"Average precision = {ap_value:.4f}",
    )

    ax.axhline(
        baseline,
        linestyle="--",
        label=f"Positive prevalence = {baseline:.4f}",
    )

    ax.set_xlabel(
        "Recall"
    )
    ax.set_ylabel(
        "Precision"
    )
    ax.set_title(
        title
    )
    ax.set_xlim(
        0,
        1,
    )
    ax.set_ylim(
        0,
        1.01,
    )
    ax.legend(
        loc="best"
    )
    ax.grid(
        alpha=0.25
    )

    fig.tight_layout()

    save_figure(
        fig,
        base_path,
    )


# =============================================================================
# BALANCED UNDERSAMPLING
# =============================================================================

def balanced_indices(
    y_true: np.ndarray,
    fraction_minority: float,
    seed: int,
) -> np.ndarray:
    y = np.asarray(
        y_true,
        dtype=int,
    )

    unique_classes, counts = np.unique(
        y,
        return_counts=True,
    )

    if len(unique_classes) != 2:
        raise ValueError(
            "Balanced undersampling requires exactly two classes."
        )

    minority_class = unique_classes[
        np.argmin(counts)
    ]
    majority_class = unique_classes[
        np.argmax(counts)
    ]

    minority_idx = np.flatnonzero(
        y == minority_class
    )

    majority_idx = np.flatnonzero(
        y == majority_class
    )

    n_pick = int(
        round(
            len(minority_idx)
            * fraction_minority
        )
    )

    n_pick = max(
        1,
        min(
            n_pick,
            len(minority_idx),
            len(majority_idx),
        ),
    )

    rng = np.random.default_rng(
        seed
    )

    chosen_minority = rng.choice(
        minority_idx,
        size=n_pick,
        replace=False,
    )

    chosen_majority = rng.choice(
        majority_idx,
        size=n_pick,
        replace=False,
    )

    selected = np.concatenate([
        chosen_minority,
        chosen_majority,
    ])

    rng.shuffle(
        selected
    )

    return selected


def flatten_report_iteration(
    report: Dict[str, Any],
    iteration: int,
) -> List[Dict[str, Any]]:
    rows: List[Dict[str, Any]] = []

    for label, values in report.items():
        if isinstance(
            values,
            dict,
        ):
            rows.append({
                "iteration": iteration,
                "label": label,
                "precision":
                    float(
                        values.get(
                            "precision",
                            np.nan,
                        )
                    ),
                "recall":
                    float(
                        values.get(
                            "recall",
                            np.nan,
                        )
                    ),
                "f1-score":
                    float(
                        values.get(
                            "f1-score",
                            np.nan,
                        )
                    ),
                "support":
                    float(
                        values.get(
                            "support",
                            np.nan,
                        )
                    ),
            })

        else:
            rows.append({
                "iteration": iteration,
                "label": label,
                "precision": np.nan,
                "recall": np.nan,
                "f1-score": float(values),
                "support": np.nan,
            })

    return rows


def repeated_balanced_evaluation(
    y_true: np.ndarray,
    probability_class1: np.ndarray,
    threshold: float,
    seed0: int,
) -> Dict[str, Any]:
    """
    Repeatedly evaluate balanced subsets of an already-predicted dataset.

    The model is NOT retrained and probabilities are NOT recomputed.
    """
    y = np.asarray(
        y_true,
        dtype=int,
    )

    p = np.asarray(
        probability_class1,
        dtype=float,
    )

    if len(y) != len(p):
        raise ValueError(
            "Balanced evaluation target/probability length mismatch."
        )

    iteration_metric_rows: List[
        Dict[str, Any]
    ] = []

    classification_report_rows: List[
        Dict[str, Any]
    ] = []

    confusion_matrices: List[
        np.ndarray
    ] = []

    normalized_confusion_matrices: List[
        np.ndarray
    ] = []

    subset_size: Optional[int] = None

    for iteration in range(
        N_BALANCED_ITERATIONS
    ):
        idx = balanced_indices(
            y_true=y,
            fraction_minority=
                BALANCED_MINORITY_FRACTION,
            seed=seed0 + iteration,
        )

        y_i = y[idx]
        p_i = p[idx]

        (
            metrics_i,
            cm_i,
            normalized_cm_i,
            pred_i,
        ) = compute_metrics(
            y_true=y_i,
            probability_class1=p_i,
            threshold=threshold,
        )

        subset_size = int(
            len(idx)
        )

        metric_row = {
            "iteration": iteration,
            "seed": seed0 + iteration,
            "rows": int(len(idx)),
            "class_0_rows":
                int(
                    np.sum(
                        y_i == 0
                    )
                ),
            "class_1_rows":
                int(
                    np.sum(
                        y_i == 1
                    )
                ),
            **metrics_i,
        }

        iteration_metric_rows.append(
            metric_row
        )

        report_i = (
            classification_report_dict(
                y_i,
                pred_i,
            )
        )

        classification_report_rows.extend(
            flatten_report_iteration(
                report_i,
                iteration,
            )
        )

        confusion_matrices.append(
            cm_i.astype(float)
        )

        normalized_confusion_matrices.append(
            normalized_cm_i.astype(float)
        )

    iteration_metrics_df = pd.DataFrame(
        iteration_metric_rows
    )

    all_classification_reports_df = (
        pd.DataFrame(
            classification_report_rows
        )
    )

    numeric_metric_columns = [
        column
        for column in iteration_metrics_df.columns
        if column
        not in {
            "iteration",
            "seed",
        }
        and pd.api.types.is_numeric_dtype(
            iteration_metrics_df[column]
        )
    ]

    metrics_mean = {
        column:
            float(
                iteration_metrics_df[
                    column
                ].mean()
            )
        for column in numeric_metric_columns
    }

    metrics_std = {
        column:
            float(
                iteration_metrics_df[
                    column
                ].std(
                    ddof=1
                )
            )
        for column in numeric_metric_columns
    }

    report_metric_columns = [
        "precision",
        "recall",
        "f1-score",
        "support",
    ]

    report_mean_df = (
        all_classification_reports_df
        .groupby(
            "label",
            sort=False,
        )[report_metric_columns]
        .mean()
        .reset_index()
    )

    report_std_df = (
        all_classification_reports_df
        .groupby(
            "label",
            sort=False,
        )[report_metric_columns]
        .std(
            ddof=1
        )
        .reset_index()
    )

    mean_cm = np.mean(
        np.stack(
            confusion_matrices,
            axis=0,
        ),
        axis=0,
    )

    std_cm = np.std(
        np.stack(
            confusion_matrices,
            axis=0,
        ),
        axis=0,
        ddof=1,
    )

    mean_normalized_cm = np.mean(
        np.stack(
            normalized_confusion_matrices,
            axis=0,
        ),
        axis=0,
    )

    std_normalized_cm = np.std(
        np.stack(
            normalized_confusion_matrices,
            axis=0,
        ),
        axis=0,
        ddof=1,
    )

    return {
        "iterations":
            N_BALANCED_ITERATIONS,
        "minority_fraction":
            BALANCED_MINORITY_FRACTION,
        "subset_size":
            subset_size,
        "metrics_mean":
            metrics_mean,
        "metrics_std":
            metrics_std,
        "mean_confusion_matrix":
            mean_cm,
        "std_confusion_matrix":
            std_cm,
        "mean_normalized_confusion_matrix":
            mean_normalized_cm,
        "std_normalized_confusion_matrix":
            std_normalized_cm,
        "iteration_metrics_df":
            iteration_metrics_df,
        "all_classification_reports_df":
            all_classification_reports_df,
        "classification_report_mean_df":
            report_mean_df,
        "classification_report_std_df":
            report_std_df,
    }


# =============================================================================
# SAVE ONE DATASET EVALUATION
# =============================================================================

def evaluate_one_dataset(
    dataset_key: str,
    df: pd.DataFrame,
    model: CatBoostClassifier,
    features: List[str],
    threshold: float,
    seed0: int,
) -> Dict[str, Any]:
    display_name = DATASET_DISPLAY_NAMES[
        dataset_key
    ]

    interpretation = DATASET_INTERPRETATION[
        dataset_key
    ]

    dataset_dir = (
        OUTPUT_DIR
        / dataset_key
    )

    raw_dir = (
        dataset_dir
        / "full_natural_distribution"
    )

    balanced_dir = (
        dataset_dir
        / "balanced_undersampled"
    )

    ensure_dir(
        raw_dir
    )

    ensure_dir(
        balanced_dir
    )

    print()
    print("=" * 88)
    print(
        f"EVALUATING: {display_name}"
    )
    print("=" * 88)

    if TARGET not in df.columns:
        raise ValueError(
            f"{dataset_key}: target '{TARGET}' missing."
        )

    y_series = validate_binary_target(
        df[TARGET],
        dataset_key,
    )

    X, preprocessing_report = (
        preprocess_numeric_features(
            df=df,
            features=features,
            dataset_name=dataset_key,
        )
    )

    y = y_series.to_numpy(
        dtype=int
    )

    print(
        f"[DATA] rows={len(df):,} "
        f"class_counts={class_counts(y)}"
    )

    # ---------------------------------------------------------------------
    # Predict ONCE on the complete dataset.
    # ---------------------------------------------------------------------
    probabilities = np.asarray(
        model.predict_proba(
            X
        ),
        dtype=float,
    )

    if (
        probabilities.ndim != 2
        or probabilities.shape[1] != 2
    ):
        raise ValueError(
            f"{dataset_key}: expected CatBoost binary "
            "predict_proba output shape (n,2), got "
            f"{probabilities.shape}."
        )

    p_class0 = probabilities[:, 0]
    p_class1 = probabilities[:, 1]

    (
        full_metrics,
        full_cm,
        full_normalized_cm,
        full_pred,
    ) = compute_metrics(
        y_true=y,
        probability_class1=p_class1,
        threshold=threshold,
    )

    full_report_dict = (
        classification_report_dict(
            y,
            full_pred,
        )
    )

    full_report_text = (
        classification_report_text(
            y,
            full_pred,
        )
    )

    full_report_df = (
        classification_report_to_dataframe(
            full_report_dict
        )
    )

    # ---------------------------------------------------------------------
    # Save full / natural-distribution artifacts.
    # ---------------------------------------------------------------------
    write_json(
        raw_dir
        / "metrics.json",
        {
            "dataset":
                dataset_key,
            "dataset_display_name":
                display_name,
            "interpretation":
                interpretation,
            "rows":
                int(len(df)),
            "class_counts":
                class_counts(y),
            "class_fractions":
                class_fractions(y),
            "threshold":
                threshold,
            "metrics":
                full_metrics,
            "confusion_matrix":
                full_cm.astype(
                    int
                ).tolist(),
            "confusion_matrix_normalized_true":
                full_normalized_cm.tolist(),
            "preprocessing":
                preprocessing_report,
        },
    )

    (
        confusion_matrix_dataframe(
            full_cm.astype(int)
        )
        .to_csv(
            raw_dir
            / "confusion_matrix.csv"
        )
    )

    (
        confusion_matrix_dataframe(
            full_normalized_cm
        )
        .to_csv(
            raw_dir
            / "confusion_matrix_normalized_true.csv"
        )
    )

    full_report_df.to_csv(
        raw_dir
        / "classification_report.csv",
        index=False,
    )

    (
        raw_dir
        / "classification_report.txt"
    ).write_text(
        full_report_text,
        encoding="utf-8",
    )

    if SAVE_PREDICTIONS:
        prediction_output = (
            df.copy()
            .reset_index(
                drop=True
            )
        )

        prediction_output[
            f"{TARGET}_probability_class0"
        ] = p_class0

        prediction_output[
            f"{TARGET}_probability_class1"
        ] = p_class1

        prediction_output[
            f"{TARGET}_probability_threshold"
        ] = threshold

        prediction_output[
            f"{TARGET}_predicted"
        ] = full_pred

        prediction_output.to_csv(
            raw_dir
            / "predictions.csv",
            index=False,
        )

    plot_confusion_matrix(
        cm=full_cm,
        title=(
            f"{display_name}\n"
            "Confusion matrix"
        ),
        base_path=(
            raw_dir
            / "confusion_matrix"
        ),
        value_format="integer",
    )

    plot_confusion_matrix(
        cm=full_normalized_cm,
        title=(
            f"{display_name}\n"
            "Confusion matrix normalized by true class"
        ),
        base_path=(
            raw_dir
            / "confusion_matrix_normalized_true"
        ),
        value_format="float",
    )

    plot_roc_curve(
        y_true=y,
        probability_class1=p_class1,
        title=(
            f"{display_name}\n"
            "ROC curve"
        ),
        base_path=(
            raw_dir
            / "roc_curve"
        ),
    )

    plot_precision_recall_curve(
        y_true=y,
        probability_class1=p_class1,
        title=(
            f"{display_name}\n"
            "Precision-recall curve"
        ),
        base_path=(
            raw_dir
            / "precision_recall_curve"
        ),
    )

    # ---------------------------------------------------------------------
    # Repeated balanced undersampled evaluation.
    # ---------------------------------------------------------------------
    print(
        f"[BALANCED] "
        f"{N_BALANCED_ITERATIONS} iterations, "
        f"minority_fraction="
        f"{BALANCED_MINORITY_FRACTION}"
    )

    balanced = (
        repeated_balanced_evaluation(
            y_true=y,
            probability_class1=p_class1,
            threshold=threshold,
            seed0=seed0,
        )
    )

    balanced[
        "iteration_metrics_df"
    ].to_csv(
        balanced_dir
        / "balanced_iteration_metrics.csv",
        index=False,
    )

    balanced[
        "all_classification_reports_df"
    ].to_csv(
        balanced_dir
        / "balanced_classification_reports_all_iterations.csv",
        index=False,
    )

    balanced[
        "classification_report_mean_df"
    ].to_csv(
        balanced_dir
        / "balanced_classification_report_mean.csv",
        index=False,
    )

    balanced[
        "classification_report_std_df"
    ].to_csv(
        balanced_dir
        / "balanced_classification_report_std.csv",
        index=False,
    )

    (
        confusion_matrix_dataframe(
            balanced[
                "mean_confusion_matrix"
            ]
        )
        .to_csv(
            balanced_dir
            / "mean_confusion_matrix.csv"
        )
    )

    (
        confusion_matrix_dataframe(
            balanced[
                "std_confusion_matrix"
            ]
        )
        .to_csv(
            balanced_dir
            / "std_confusion_matrix.csv"
        )
    )

    (
        confusion_matrix_dataframe(
            balanced[
                "mean_normalized_confusion_matrix"
            ]
        )
        .to_csv(
            balanced_dir
            / "mean_confusion_matrix_normalized_true.csv"
        )
    )

    (
        confusion_matrix_dataframe(
            balanced[
                "std_normalized_confusion_matrix"
            ]
        )
        .to_csv(
            balanced_dir
            / "std_confusion_matrix_normalized_true.csv"
        )
    )

    balanced_summary_json = {
        "dataset":
            dataset_key,
        "dataset_display_name":
            display_name,
        "interpretation":
            interpretation,
        "rows_in_original_dataset":
            int(len(df)),
        "original_class_counts":
            class_counts(y),
        "threshold":
            threshold,
        "iterations":
            balanced[
                "iterations"
            ],
        "minority_fraction":
            balanced[
                "minority_fraction"
            ],
        "rows_per_balanced_subset":
            balanced[
                "subset_size"
            ],
        "metrics_mean":
            balanced[
                "metrics_mean"
            ],
        "metrics_std":
            balanced[
                "metrics_std"
            ],
        "mean_confusion_matrix":
            balanced[
                "mean_confusion_matrix"
            ].tolist(),
        "std_confusion_matrix":
            balanced[
                "std_confusion_matrix"
            ].tolist(),
        "mean_normalized_confusion_matrix":
            balanced[
                "mean_normalized_confusion_matrix"
            ].tolist(),
        "std_normalized_confusion_matrix":
            balanced[
                "std_normalized_confusion_matrix"
            ].tolist(),
    }

    write_json(
        balanced_dir
        / "balanced_summary.json",
        balanced_summary_json,
    )

    plot_confusion_matrix(
        cm=balanced[
            "mean_confusion_matrix"
        ],
        title=(
            f"{display_name}\n"
            "Mean balanced confusion matrix"
        ),
        base_path=(
            balanced_dir
            / "mean_confusion_matrix"
        ),
        value_format="float",
    )

    plot_confusion_matrix(
        cm=balanced[
            "mean_normalized_confusion_matrix"
        ],
        title=(
            f"{display_name}\n"
            "Mean balanced confusion matrix "
            "normalized by true class"
        ),
        base_path=(
            balanced_dir
            / "mean_confusion_matrix_normalized_true"
        ),
        value_format="float",
    )

    # ---------------------------------------------------------------------
    # Human-readable per-dataset report.
    # ---------------------------------------------------------------------
    report_lines: List[str] = []

    report_lines.append(
        f"DIGIGARD STAGE 04 - {display_name}"
    )
    report_lines.append(
        "=" * 72
    )
    report_lines.append(
        f"TARGET: {TARGET}"
    )
    report_lines.append(
        f"MODEL_RUN: {MODEL_RUN}"
    )
    report_lines.append(
        f"ROWS: {len(df)}"
    )
    report_lines.append(
        f"CLASS_COUNTS: {class_counts(y)}"
    )
    report_lines.append(
        f"THRESHOLD: {threshold}"
    )
    report_lines.append("")
    report_lines.append(
        "INTERPRETATION:"
    )
    report_lines.append(
        f"  {interpretation}"
    )
    report_lines.append("")

    report_lines.append(
        "=== FULL / NATURAL DISTRIBUTION ==="
    )
    report_lines.append(
        full_report_text
    )
    report_lines.append("")

    report_lines.append(
        "Additional metrics:"
    )

    for metric_name in [
        "accuracy",
        "balanced_accuracy",
        "precision",
        "recall_sensitivity",
        "specificity",
        "f1",
        "mcc",
        "roc_auc",
        "average_precision",
        "brier_score",
        "log_loss",
    ]:
        report_lines.append(
            f"  {metric_name}: "
            f"{full_metrics[metric_name]:.6g}"
        )

    report_lines.append("")
    report_lines.append(
        "Confusion matrix:"
    )
    report_lines.append(
        str(
            full_cm.astype(
                int
            ).tolist()
        )
    )
    report_lines.append("")

    report_lines.append(
        "=== REPEATED BALANCED UNDERSAMPLING ==="
    )
    report_lines.append(
        f"Iterations: "
        f"{N_BALANCED_ITERATIONS}"
    )
    report_lines.append(
        f"Minority fraction per iteration: "
        f"{BALANCED_MINORITY_FRACTION}"
    )
    report_lines.append(
        f"Rows per balanced subset: "
        f"{balanced['subset_size']}"
    )
    report_lines.append("")

    report_lines.append(
        "Mean metrics:"
    )

    for metric_name in [
        "accuracy",
        "balanced_accuracy",
        "precision",
        "recall_sensitivity",
        "specificity",
        "f1",
        "mcc",
        "roc_auc",
        "average_precision",
        "brier_score",
        "log_loss",
    ]:
        mean_value = (
            balanced[
                "metrics_mean"
            ].get(
                metric_name,
                float("nan"),
            )
        )

        std_value = (
            balanced[
                "metrics_std"
            ].get(
                metric_name,
                float("nan"),
            )
        )

        report_lines.append(
            f"  {metric_name}: "
            f"{mean_value:.6g} "
            f"+/- {std_value:.6g}"
        )

    report_lines.append("")
    report_lines.append(
        "Mean balanced confusion matrix:"
    )
    report_lines.append(
        str(
            balanced[
                "mean_confusion_matrix"
            ].tolist()
        )
    )

    (
        dataset_dir
        / "EVALUATION_REPORT.txt"
    ).write_text(
        "\n".join(
            report_lines
        ),
        encoding="utf-8",
    )

    print(
        "[RAW] "
        f"accuracy={full_metrics['accuracy']:.6f} "
        f"bacc={full_metrics['balanced_accuracy']:.6f} "
        f"f1={full_metrics['f1']:.6f} "
        f"auc={full_metrics['roc_auc']:.6f}"
    )

    print(
        "[BAL] "
        f"accuracy="
        f"{balanced['metrics_mean']['accuracy']:.6f} "
        f"bacc="
        f"{balanced['metrics_mean']['balanced_accuracy']:.6f} "
        f"f1="
        f"{balanced['metrics_mean']['f1']:.6f} "
        f"auc="
        f"{balanced['metrics_mean']['roc_auc']:.6f}"
    )

    return {
        "dataset_key":
            dataset_key,
        "display_name":
            display_name,
        "interpretation":
            interpretation,
        "rows":
            int(len(df)),
        "class_counts":
            class_counts(y),
        "class_fractions":
            class_fractions(y),
        "preprocessing":
            preprocessing_report,
        "full_metrics":
            full_metrics,
        "full_confusion_matrix":
            full_cm.astype(
                int
            ).tolist(),
        "full_normalized_confusion_matrix":
            full_normalized_cm.tolist(),
        "balanced_iterations":
            N_BALANCED_ITERATIONS,
        "balanced_minority_fraction":
            BALANCED_MINORITY_FRACTION,
        "balanced_subset_size":
            balanced[
                "subset_size"
            ],
        "balanced_metrics_mean":
            balanced[
                "metrics_mean"
            ],
        "balanced_metrics_std":
            balanced[
                "metrics_std"
            ],
        "balanced_mean_confusion_matrix":
            balanced[
                "mean_confusion_matrix"
            ].tolist(),
        "balanced_mean_normalized_confusion_matrix":
            balanced[
                "mean_normalized_confusion_matrix"
            ].tolist(),
    }


# =============================================================================
# MASTER SUMMARY
# =============================================================================

def make_master_summary_dataframe(
    results: Dict[str, Dict[str, Any]],
) -> pd.DataFrame:
    rows: List[Dict[str, Any]] = []

    main_metrics = [
        "accuracy",
        "balanced_accuracy",
        "precision",
        "recall_sensitivity",
        "specificity",
        "f1",
        "mcc",
        "roc_auc",
        "average_precision",
        "brier_score",
        "log_loss",
    ]

    for dataset_key in DATASET_ORDER:
        result = results[
            dataset_key
        ]

        row: Dict[str, Any] = {
            "dataset":
                dataset_key,
            "dataset_display_name":
                result[
                    "display_name"
                ],
            "rows":
                result[
                    "rows"
                ],
            "class_0_rows":
                result[
                    "class_counts"
                ].get(
                    "0",
                    0,
                ),
            "class_1_rows":
                result[
                    "class_counts"
                ].get(
                    "1",
                    0,
                ),
            "balanced_subset_size":
                result[
                    "balanced_subset_size"
                ],
            "balanced_iterations":
                result[
                    "balanced_iterations"
                ],
        }

        for metric_name in main_metrics:
            row[
                f"full_{metric_name}"
            ] = (
                result[
                    "full_metrics"
                ].get(
                    metric_name,
                    np.nan,
                )
            )

            row[
                f"balanced_mean_{metric_name}"
            ] = (
                result[
                    "balanced_metrics_mean"
                ].get(
                    metric_name,
                    np.nan,
                )
            )

            row[
                f"balanced_std_{metric_name}"
            ] = (
                result[
                    "balanced_metrics_std"
                ].get(
                    metric_name,
                    np.nan,
                )
            )

        rows.append(
            row
        )

    return pd.DataFrame(
        rows
    )


def make_comparison_metrics_long_dataframe(
    results: Dict[str, Dict[str, Any]],
) -> pd.DataFrame:
    main_metrics = [
        "accuracy",
        "balanced_accuracy",
        "precision",
        "recall_sensitivity",
        "specificity",
        "f1",
        "mcc",
        "roc_auc",
        "average_precision",
        "brier_score",
        "log_loss",
    ]

    rows: List[Dict[str, Any]] = []

    for dataset_key in DATASET_ORDER:
        result = results[
            dataset_key
        ]

        for metric_name in main_metrics:
            rows.append({
                "dataset":
                    dataset_key,
                "dataset_display_name":
                    result[
                        "display_name"
                    ],
                "evaluation":
                    "full_natural_distribution",
                "metric":
                    metric_name,
                "mean_or_value":
                    result[
                        "full_metrics"
                    ].get(
                        metric_name,
                        np.nan,
                    ),
                "std":
                    np.nan,
            })

            rows.append({
                "dataset":
                    dataset_key,
                "dataset_display_name":
                    result[
                        "display_name"
                    ],
                "evaluation":
                    "balanced_undersampled",
                "metric":
                    metric_name,
                "mean_or_value":
                    result[
                        "balanced_metrics_mean"
                    ].get(
                        metric_name,
                        np.nan,
                    ),
                "std":
                    result[
                        "balanced_metrics_std"
                    ].get(
                        metric_name,
                        np.nan,
                    ),
            })

    return pd.DataFrame(
        rows
    )


# =============================================================================
# MAIN
# =============================================================================

def main() -> None:
    start_time = time.time()

    # ---------------------------------------------------------------------
    # Validate required upstream artifacts.
    # ---------------------------------------------------------------------
    for required_path in [
        TRAIN_CSV,
        TEST_CSV,
        MODEL_MANIFEST,
        MODEL_FEATURES_JSON,
        MODEL_PATH,
    ]:
        if not required_path.exists():
            raise SystemExit(
                "Required upstream artifact not found:\n"
                f"  {required_path.resolve()}"
            )

    if OUTPUT_DIR.exists() and not OVERWRITE_EXISTING_EVALUATION:
        raise SystemExit(
            "Stage-04 output directory already exists and "
            "OVERWRITE_EXISTING_EVALUATION=False:\n"
            f"  {OUTPUT_DIR.resolve()}"
        )

    ensure_dir(
        OUTPUT_DIR
    )

    print("=" * 88)
    print(
        "DIGIGARD STAGE 04 - CATBOOST CLASSIFIER EVALUATION"
    )
    print("=" * 88)
    print(
        f"TARGET       : {TARGET}"
    )
    print(
        f"MODEL_RUN    : {MODEL_RUN}"
    )
    print(
        f"MODEL_PATH   : {MODEL_PATH.resolve()}"
    )
    print(
        f"TRAIN_CSV    : {TRAIN_CSV.resolve()}"
    )
    print(
        f"TEST_CSV     : {TEST_CSV.resolve()}"
    )
    print(
        f"OUTPUT_DIR   : {OUTPUT_DIR.resolve()}"
    )
    print()

    # ---------------------------------------------------------------------
    # Load Stage-03 model metadata, feature contract and CatBoost model.
    # ---------------------------------------------------------------------
    manifest = load_model_manifest()
    features = load_feature_contract()
    threshold = resolve_threshold(
        manifest
    )
    model = load_catboost_model()

    print(
        f"[MODEL] Loaded CatBoostClassifier with "
        f"{len(features)} features."
    )

    # ---------------------------------------------------------------------
    # Load Stage-02 train and test data.
    # ---------------------------------------------------------------------
    train_df = pd.read_csv(
        TRAIN_CSV,
        low_memory=False,
    )

    test_df = pd.read_csv(
        TEST_CSV,
        low_memory=False,
    )

    # Add provenance only for the combined full-data prediction output.
    train_for_full = train_df.copy()
    test_for_full = test_df.copy()

    train_for_full[
        "DIGIGARD_split_origin"
    ] = "train"

    test_for_full[
        "DIGIGARD_split_origin"
    ] = "test"

    full_df = pd.concat(
        [
            train_for_full,
            test_for_full,
        ],
        ignore_index=True,
        sort=False,
    )

    datasets = {
        "full_dataset":
            full_df,
        "training_dataset":
            train_df,
        "testing_dataset":
            test_df,
    }

    seeds = {
        "full_dataset":
            FULL_DATASET_BALANCE_SEED,
        "training_dataset":
            TRAIN_DATASET_BALANCE_SEED,
        "testing_dataset":
            TEST_DATASET_BALANCE_SEED,
    }

    results: Dict[
        str,
        Dict[str, Any]
    ] = {}

    # ---------------------------------------------------------------------
    # Evaluate all three requested datasets.
    # ---------------------------------------------------------------------
    for dataset_key in DATASET_ORDER:
        results[
            dataset_key
        ] = evaluate_one_dataset(
            dataset_key=
                dataset_key,
            df=
                datasets[
                    dataset_key
                ],
            model=
                model,
            features=
                features,
            threshold=
                threshold,
            seed0=
                seeds[
                    dataset_key
                ],
        )

    # ---------------------------------------------------------------------
    # Master comparison artifacts.
    # ---------------------------------------------------------------------
    master_summary_df = (
        make_master_summary_dataframe(
            results
        )
    )

    master_summary_path = (
        OUTPUT_DIR
        / "evaluation_summary.csv"
    )

    master_summary_df.to_csv(
        master_summary_path,
        index=False,
    )

    comparison_long_df = (
        make_comparison_metrics_long_dataframe(
            results
        )
    )

    comparison_long_path = (
        OUTPUT_DIR
        / "evaluation_metrics_long.csv"
    )

    comparison_long_df.to_csv(
        comparison_long_path,
        index=False,
    )

    elapsed_seconds = float(
        time.time()
        - start_time
    )

    # ---------------------------------------------------------------------
    # Global machine-readable report.
    # ---------------------------------------------------------------------
    master_report = {
        "pipeline":
            "DIGIGARD",
        "stage":
            4,
        "stage_name":
            "catboost_classifier_evaluation",
        "target":
            TARGET,
        "model_run":
            MODEL_RUN,
        "model_type":
            "CATBOOST",
        "model_path":
            str(
                MODEL_PATH.resolve()
            ),
        "model_manifest":
            str(
                MODEL_MANIFEST.resolve()
            ),
        "features_json":
            str(
                MODEL_FEATURES_JSON.resolve()
            ),
        "feature_count":
            len(features),
        "features":
            features,
        "probability_method":
            "predict_proba(X)[:, 1]",
        "positive_class":
            POSITIVE_CLASS,
        "threshold":
            threshold,
        "balanced_evaluation": {
            "iterations":
                N_BALANCED_ITERATIONS,
            "minority_fraction":
                BALANCED_MINORITY_FRACTION,
            "meaning":
                (
                    "Each iteration samples the configured fraction of the "
                    "minority class and the same number of majority examples. "
                    "The already-trained model is not retrained."
                ),
        },
        "datasets":
            results,
        "interpretation": {
            "testing_dataset":
                DATASET_INTERPRETATION[
                    "testing_dataset"
                ],
            "training_dataset":
                DATASET_INTERPRETATION[
                    "training_dataset"
                ],
            "full_dataset":
                DATASET_INTERPRETATION[
                    "full_dataset"
                ],
        },
        "artifacts": {
            "evaluation_summary_csv":
                str(
                    master_summary_path.resolve()
                ),
            "evaluation_metrics_long_csv":
                str(
                    comparison_long_path.resolve()
                ),
        },
        "environment": {
            "python":
                sys.version,
            "platform":
                platform.platform(),
            "numpy":
                safe_package_version(
                    "numpy"
                ),
            "pandas":
                safe_package_version(
                    "pandas"
                ),
            "scikit_learn":
                safe_package_version(
                    "scikit-learn"
                ),
            "matplotlib":
                safe_package_version(
                    "matplotlib"
                ),
            "catboost":
                safe_package_version(
                    "catboost"
                ),
        },
        "elapsed_seconds":
            elapsed_seconds,
    }

    # Remove DataFrames from nested balanced internals:
    # evaluate_one_dataset already returned only JSON-safe objects.
    master_report_path = (
        OUTPUT_DIR
        / "evaluation_report.json"
    )

    write_json(
        master_report_path,
        master_report,
    )

    # ---------------------------------------------------------------------
    # Global human-readable report.
    # ---------------------------------------------------------------------
    report_lines: List[str] = []

    report_lines.append(
        "DIGIGARD STAGE 04 - CATBOOST CLASSIFIER EVALUATION"
    )
    report_lines.append(
        "=" * 78
    )
    report_lines.append(
        f"TARGET: {TARGET}"
    )
    report_lines.append(
        f"MODEL_RUN: {MODEL_RUN}"
    )
    report_lines.append(
        f"MODEL_PATH: {MODEL_PATH.resolve()}"
    )
    report_lines.append(
        f"N_FEATURES: {len(features)}"
    )
    report_lines.append(
        f"PROBABILITY_THRESHOLD: {threshold}"
    )
    report_lines.append(
        f"BALANCED_ITERATIONS: "
        f"{N_BALANCED_ITERATIONS}"
    )
    report_lines.append(
        f"BALANCED_MINORITY_FRACTION: "
        f"{BALANCED_MINORITY_FRACTION}"
    )
    report_lines.append("")

    report_lines.append(
        "=== INTERPRETATION ==="
    )
    report_lines.append(
        "TESTING DATASET:"
    )
    report_lines.append(
        f"  {DATASET_INTERPRETATION['testing_dataset']}"
    )
    report_lines.append(
        "TRAINING DATASET:"
    )
    report_lines.append(
        f"  {DATASET_INTERPRETATION['training_dataset']}"
    )
    report_lines.append(
        "FULL TARGET DATASET:"
    )
    report_lines.append(
        f"  {DATASET_INTERPRETATION['full_dataset']}"
    )
    report_lines.append("")

    metric_order = [
        "accuracy",
        "balanced_accuracy",
        "precision",
        "recall_sensitivity",
        "specificity",
        "f1",
        "mcc",
        "roc_auc",
        "average_precision",
        "brier_score",
        "log_loss",
    ]

    for dataset_key in DATASET_ORDER:
        result = results[
            dataset_key
        ]

        report_lines.append(
            "=" * 78
        )
        report_lines.append(
            result[
                "display_name"
            ]
        )
        report_lines.append(
            "=" * 78
        )
        report_lines.append(
            f"Rows: "
            f"{result['rows']}"
        )
        report_lines.append(
            f"Class counts: "
            f"{result['class_counts']}"
        )
        report_lines.append("")

        report_lines.append(
            "FULL / NATURAL DISTRIBUTION:"
        )

        for metric_name in metric_order:
            report_lines.append(
                f"  {metric_name}: "
                f"{result['full_metrics'][metric_name]:.6g}"
            )

        report_lines.append("")
        report_lines.append(
            "BALANCED UNDERSAMPLING "
            "(mean +/- std):"
        )

        for metric_name in metric_order:
            mean_value = (
                result[
                    "balanced_metrics_mean"
                ].get(
                    metric_name,
                    float("nan"),
                )
            )

            std_value = (
                result[
                    "balanced_metrics_std"
                ].get(
                    metric_name,
                    float("nan"),
                )
            )

            report_lines.append(
                f"  {metric_name}: "
                f"{mean_value:.6g} "
                f"+/- {std_value:.6g}"
            )

        report_lines.append("")

    human_report_path = (
        OUTPUT_DIR
        / "EVALUATION_REPORT.txt"
    )

    human_report_path.write_text(
        "\n".join(
            report_lines
        ),
        encoding="utf-8",
    )

    # ---------------------------------------------------------------------
    # Run configuration.
    # ---------------------------------------------------------------------
    run_config = {
        "pipeline":
            "DIGIGARD",
        "stage":
            4,
        "target":
            TARGET,
        "model_run":
            MODEL_RUN,
        "model_type":
            "CATBOOST",
        "random_state":
            RANDOM_STATE,
        "train_csv":
            str(TRAIN_CSV),
        "test_csv":
            str(TEST_CSV),
        "model_path":
            str(MODEL_PATH),
        "model_manifest":
            str(MODEL_MANIFEST),
        "features_json":
            str(MODEL_FEATURES_JSON),
        "output_dir":
            str(OUTPUT_DIR),
        "threshold_override":
            THRESHOLD_OVERRIDE,
        "resolved_threshold":
            threshold,
        "balanced_iterations":
            N_BALANCED_ITERATIONS,
        "balanced_minority_fraction":
            BALANCED_MINORITY_FRACTION,
        "save_predictions":
            SAVE_PREDICTIONS,
        "save_plots":
            SAVE_PLOTS,
        "save_png":
            SAVE_PNG,
        "save_eps":
            SAVE_EPS,
    }

    write_json(
        OUTPUT_DIR
        / "evaluation_config.json",
        run_config,
    )

    # ---------------------------------------------------------------------
    # Final console output.
    # ---------------------------------------------------------------------
    print()
    print("=" * 88)
    print(
        "DIGIGARD STAGE 04 COMPLETE"
    )
    print("=" * 88)

    for dataset_key in DATASET_ORDER:
        result = results[
            dataset_key
        ]

        print(
            f"{result['display_name']}:"
        )

        print(
            f"  FULL     "
            f"bacc="
            f"{result['full_metrics']['balanced_accuracy']:.6f} "
            f"f1="
            f"{result['full_metrics']['f1']:.6f} "
            f"auc="
            f"{result['full_metrics']['roc_auc']:.6f}"
        )

        print(
            f"  BALANCED "
            f"bacc="
            f"{result['balanced_metrics_mean']['balanced_accuracy']:.6f} "
            f"f1="
            f"{result['balanced_metrics_mean']['f1']:.6f} "
            f"auc="
            f"{result['balanced_metrics_mean']['roc_auc']:.6f}"
        )

    print()
    print(
        f"[OK] Output directory      -> "
        f"{OUTPUT_DIR}"
    )
    print(
        f"[OK] Master summary CSV    -> "
        f"{master_summary_path}"
    )
    print(
        f"[OK] Machine report        -> "
        f"{master_report_path}"
    )
    print(
        f"[OK] Human report          -> "
        f"{human_report_path}"
    )


if __name__ == "__main__":
    main()
